site_name: Desenho de Software
site_description: Repositório da disciplina de Desenho de software
repo_url: https://github.com/desenho-de-software-2019-02/Document-o
site_dir: site
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: 'images/icon.jpeg'
  favicon: 'images/icon.jpeg'
  palette:
    primary: 'blue'
  language: 'pt'

plugins:
  - search
nav:
  - Home: 'docs/index.md'
  - Definições de projeto: 
    - Discução de tema: 'docs/discucao_tema.md'
  