site_name:  Master of Puppets
site_description: Repositório da disciplina de Desenho de software
repo_url: https://github.com/desenho-de-software-2019-02/Documentation
site_dir: site
dev_addr: ‘0.0.0.0:8000
extra_css:
- 'stylesheets/extra.css'
theme:
  name: 'material'

  palette:
    primary: indigo
    accent: red
    language: 'pt'

plugins:
  - search

page:
- Home: 'docs/index.md'

