site_name:  Master of Puppets
site_description: Repositório da disciplina de Desenho de software
repo_url: https://github.com/desenho-de-software-2019-02/Documentation
site_dir: site
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
#  logo: '<a href="https://imgur.com/Y0SLT7T"><img src="https://i.imgur.com/Y0SLT7T.png?1" title="source: imgur.com"  width="70" height="50" /></a>'
#  favicon: 'img/dados_verdes.png'
  palette:
    primary: ''
  language: 'pt'

plugins:
  - search
page:
- Home : 'docs/index.md'
- Documentação: 
  - Definições de projeto: 
  - Discução de tema: 'docs/discucao_tema.md'
  - NFR's: 'docs/nfr.md'
  - Richpicture: 'docs/richpicture.md'
  - 5W2h: 'docs/5w2h.md'
  - 5W2h: 'docs/brainstorm.md'
  - Mapa mental: 'docs/mapa_mental.md'
  - TAP: 'docs/tap.md'
  

